### ISSUE TITLE
eYRC reg

### ISSUE THREAD

**Issue by Krish-venom** [ars-21/eyrc22_DB_2996#7]
Bro will you help our team for the eYRC competition and would you share your mail , it will be useful for us to clarify our doubts

**Comment by ars-21** [comment]
Do Note - this Repo was created to showcase the team's work ONLY.

- To maintain fairness in the competition, I will not be able to assist you in any form.
- If you have any doubts/queries/problems, you could use the official channel provided by e-Yantra. And the team has always been active, and solved all our queries/concerns properly.
- Learn, Enjoy, Work Hard, Believe in the process, as with e-Yantra you'll get ample opportunity to learn and implement.
- If you still wish to just connect, (DO NOTE - I WILL NOT BE HELPING IN ANY FORM), send a LinkedIn invitation using the link in my profile.

All the very best for eYRC !!! :)
